title: ShinHyeonMan 개발 블로그
description: > # this means to ignore newlines until "baseurl:"
  일단 시작해보는 블로그
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ShinHyeonMan.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
#site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: ShinHyeonMan # add your name
author-img: ShinHyeonMan.jpg # add your photo
about-author: 개발 블로그 # add description
social-open-kakao: cswsshm0627 # add your Twitter handle
#social-facebook: # add your Facebook handle
social-github: ShinHyeonMan # add your Github handle
#social-linkedin: # add your Linkedin handle
social-email: cswsshm0627@gmail.com # add your Email address

# Disqus
discus-identifier: cswsshm0627 # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
